language: python

# Test on multiple Python versions
python:
  - "3.8"
  - "3.9" 
  - "3.10"
  - "3.11"

# Use Ubuntu 20.04 (focal)
dist: focal

# Cache pip dependencies for faster builds
cache: pip

# Install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

# Set up environment variables
env:
  - PYTHONPATH=$PYTHONPATH:./src

# Commands to run before testing (syntax check)
before_script:
  - python -m py_compile src/github_api.py
  - python -m py_compile demo.py
  - python -m py_compile tests/test_github_api.py

# Commands to run tests
script:
  - python -m pytest tests/ -v --cov=src --cov-report=term-missing
  - echo "n" | python demo.py  # Run demo in non-interactive mode

# Optional: Generate coverage report and upload to codecov
after_success:
  - pip install codecov
  - codecov

# Build configuration
jobs:
  include:
    - stage: "Integration Tests"
      python: "3.9"
      script: python -m pytest tests/ -m integration -v
      if: branch = main

# Only build on main branch and pull requests
branches:
  only:
    - main
    - master

# Email notifications
notifications:
  email:
    on_success: never
    on_failure: always
