language: python

python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

dist: focal
cache: pip

env:
  global:
    - PYTHONPATH=$PYTHONPATH:./src

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest pytest-cov

before_script:
  - python -m py_compile src/github_api.py
  - python -m py_compile tests/test_github_api.py
  # NOTE: Do NOT run/compile demo.py here if it can hit the real API.

script:
  # Run ONLY unit tests (no network). Exclude integration-marked tests.
  - python -m pytest tests/ -v -m "not integration" --cov=src --cov-report=term-missing

after_success:
  - pip install codecov
  - codecov

# Do NOT run integration tests on this mocking branch
jobs:
  include: []

# Build this branch explicitly (and your main branches if you want)
branches:
  only:
    - HW03a_Mocking
    - main
    - master

notifications:
  email:
    on_success: never
    on_failure: always
